routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/prueba',function(){
//     $afiliados = App\Afiliado::find(1);
//     dd($afiliados->nombre);
// });

Route::resource('/afiliados', AfiliadosController::class);

Route::resource('sisbens', SisbenController::class);

//mrutas de autenticacion
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Afiliado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Afiliado extends Model
{
    protected $table='afiliados';
    protected $primarykey='id_afiliado';
    protected $fillable = ['n_identificacion',
    'Nombre',
    'tipo_documento',
    'direccion',
    'telefono',
    'fecha_nacimiento',
    'fecha_afiliacion',
    ];
    public $timeStamps = false;

    // relacion muchos a uno
    public function Sisben(){
        return $this->hasMany('App\Sisben');
    }
}

app/Sisben.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sisben extends Model
{
    protected $table='sisbens';
    protected $primarykey='id_sisben';
    protected $fillable = ['nivel_sisben',
    'puntaje',
    'id_afiliado'
    ];
    public $timeStamps = false;

    // relacion muchos a uno
    public function Afiliado(){
        return $this->belongsTo('App\Afiliado');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/AfiliadosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Afiliado;

class AfiliadosController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $afiliados = Afiliado::orderBy('Nombre','Desc')->paginate(3);
        return view('afiliados.index')->with('afiliados',$afiliados);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('afiliados.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->get('tipo_identificacion'));
        $afiliado = new Afiliado();
        $afiliado->n_identificacion = $request->get('n_identificacion');
        $afiliado->Nombre = $request->get('nombre');
        $afiliado->tipo_documento = $request->get('tipo_identificacion');
        $afiliado->direccion = $request->get('direccion');
        $afiliado->telefono = $request->get('telefono');
        $afiliado->fecha_nacimiento = $request->get('fecha_nacimiento');
        $afiliado->fecha_afiliacion = $request->get('fecha_afiliacion');
        $afiliado->save();
        return redirect()->route('afiliados.index')->with('alert','resgistrado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SisbenController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Sisben;
use App\Afiliado;

class SisbenController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sisbens = Sisben::all();
        return $sisbens;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/afiliados/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-18">
			<div class="card" style="width:1200px;overflow-x:hidden;">
				<div class="card-header" align="center" style="  color: black;border-radius: 10px; height: 40px">
					<h4>{{ __('Crear Afiliados') }}</h4>
				</div>
				<form method="POST" action="{{ route('afiliados.store') }}"  role="form">
							{{ csrf_field() }}
					<div class="row" align="center">
						<div class="col-sm">
							<label for="tipo_identificacion">Tipo de identificación</label>
							<select id="tipo_identificacion" type="text" name="tipo_identificacion">
								<option value="registro civil">Registro civil</option>
								<option value="Ti">Tarjeta de identidad</option>
								<option value="CC">Cedula de ciudadania</option>
							</select>
						</div>
					</div>
					<div class="row" align="center">
						<div class="col-sm">
							<label for="n_identificacion">Numero de identificación</label>
							<div class="input-group" style="width: 400px">
								<input type="text" class="form-control" id="n_identificacion" name="n_identificacion">
							</div>
						</div>
					</div>

					<div class="row" align="center">
						<div class="col-sm">
							<label for="nombre">Nombre afiliado</label>
							<div class="input-group" style="width: 400px">
								<input type="text" class="form-control" id="nombre" name="nombre">
							</div>
						</div>
					</div>

					<div class="row" align="center">
						<div class="col-sm">
							<label for="direccion">Dirección del afiliado</label>
							<div class="input-group" style="width: 400px">
								<input type="text" class="form-control" id="direccion" name="direccion">
							</div>
						</div>
					</div>

					<div class="row" align="center">
						<div class="col-sm">
							<label for="telefono">Telefono del afiliado</label>
							<div class="input-group" style="width: 400px">
								<input type="text" class="form-control" id="telefono" name="telefono">
							</div>
						</div>
					</div>

					<div class="row" align="center">
						<div class="col-sm">
							<label for="fecha_nacimiento">Fecha de nacimiento</label>
							<div class="input-group" style="width: 400px">
								<input type="text" class="form-control" id="fecha_nacimiento" name="fecha_nacimiento" placeholder="aaaa-mm-dd">
							</div>
						</div>
					</div>

					<div class="row" align="center">
						<div class="col-sm">
							<label for="fecha_afiliacion">Fecha de afiliación</label>
							<div class="input-group" style="width: 400px">
								<input type="text" class="form-control" id="fecha_afiliacion" name="fecha_afiliacion" placeholder="aaaa-mm-dd">
							</div>
						</div>
					</div>

				</br>
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12">
							<input type="submit"  value="Guardar" class="btn btn-success btn-block">
							<a href="{{ route('afiliados.index') }}" class="btn btn-info btn-block" >Atrás</a>
						</div>
					</div>
				</form>

			</div>
		</div>
	</div>
</div>
@endsection

resources/views/afiliados/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-18">
			<div class="card" style="width:1200px;overflow-x:hidden;">
				@if (session('alert'))
				<div class="alert alert-success">
					{{ session('alert') }}
				</div>
				@endif
				<div class="card-header" align="center" style="  color: black;border-radius: 10px; height: 40px">
					<h4>{{ __('Afiliados') }}</h4>
				</div>
				<div class="card-body">
					<div class="row">
						<div class="col-sm-8"></div>
						<div class="col-sm">
							<div>
								<a class="btn-Top" href="{{ route('afiliados.create') }}">
									<span class="glyphicon glyphicon-plus"></span> Nuevo Afiliado
								</a>
							</div>
						</div>
					</div>

						<table id="tabla_afiliados" class="table table-bordered">
							<thead>
								<th>Nombre</th>
								<th>Telefono</th>
								<th>Ver</th>
								<th>Editar</th>
								<th>Eliminar</th>
							</thead>
							<tbody>
								@foreach($afiliados as $afiliado)
									<tr>
										<td>{{$afiliado->Nombre}}</td>
										<td>{{$afiliado->telefono}}</td>
										<td><a href="{{route('afiliados.show',$afiliado->id_afiliado)}}"> ver</a></td>
										<td><a href="{{route('afiliados.edit',$afiliado->id_afiliado)}}"> editar</a></td>
										<td><a href="{{route('afiliados.destroy',$afiliado->id_afiliado)}}"> eliminar</a></td>
									</tr>
								@endforeach
							</tbody>
						</table>
					<div align="center">
						{{$afiliados->render()}}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/home') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ route('afiliados.index') }}">
                        Afiliados
                    </a>

                    <a class="navbar-brand" href="{{ route('sisbens.index') }}">
                        Sisben
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>